export const questions = [
  'What inspired you to start your own business?',
  'How do you stay motivated during challenging times in your business?',
  "What's the best business advice you've ever received?",
  'Share a book that has influenced your entrepreneurial journey.',
  "What's the most important skill for an entrepreneur to have?",
  'How do you balance work and personal life as an entrepreneur?',
  "What's the biggest lesson you've learned from a business failure?",
  'How do you come up with new business ideas?',
  'Share a productivity tip that helps you stay efficient in your work.',
  'How do you handle stress in your business?',
  'Who is your business idol, and why?',
  "What's the key to successful networking in the business world?",
  'Share a memorable moment from your entrepreneurial journey.',
  'How do you handle disagreements with business partners or clients?',
  "What's your favorite business-related podcast or YouTube channel?",
  'Describe your ideal workplace environment for maximum productivity.',
  "What's the most challenging aspect of running a business for you?",
  "Share a business goal you've achieved recently and how you did it.",
  "What's the impact you want your business to make in the world?",
  'How do you approach market research for a new business idea?',
  "What's your favorite business-related quote?",
  'Share a habit that has contributed to your business success.',
  'How do you adapt to changing market trends in your industry?',
  'Describe your most innovative business idea.',
  "What's your favorite tool or software for business management?",
  'Share a piece of advice you wish you had known when you started your business.',
  'How do you prioritize tasks and projects in your business?',
  "What's your favorite aspect of entrepreneurship?",
  'Describe a challenge you faced and overcame in your business.',
  'Share a resource (book, course, website) that has helped you in your business journey.',
  "What's your favorite way to celebrate business milestones?",
  'How do you build a strong team for your business?',
  'Share a marketing strategy that worked exceptionally well for your business.',
  "What's the most rewarding part of being an entrepreneur?",
  'How do you stay updated with the latest industry trends?',
  'Describe a mentorship experience that positively impacted your business.',
  'Share a lesson you learned from a business setback.',
  "What's your favorite business-related event or conference?",
  'How do you maintain a healthy work-life balance as an entrepreneur?',
  'Describe a creative marketing campaign you executed for your business.',
  "What's your favorite business-related documentary or movie?",
  "Share a goal you're currently working towards in your business.",
  'How do you stay organized with your business tasks and projects?',
  "What's your approach to time management in your business?",
  'Describe a collaboration or partnership that benefited your business.',
  'Share a piece of technology that has revolutionized your business operations.',
  "What's your favorite strategy for customer retention?",
  'How do you handle negative feedback or criticism about your business?',
  'Describe a project or product launch that was particularly successful.',
  'Share a story of a customer or client who had a significant impact on your business.',
  "What's your favorite business-related blog or website?",
  'How do you stay creative and innovative in your business ideas?',
  'Describe a time when you had to pivot your business strategy and how it turned out.',
  'Share a valuable lesson you learned from a mentor or advisor.',
  "What's your favorite aspect of your business culture?",
  'How do you handle setbacks and failures in your business?',
  "Describe a partnership or collaboration that didn't work out and the lessons learned.",
  'Share a personal habit that has positively influenced your business productivity.',
  "What's your approach to building a strong brand for your business?",
  'How do you foster a positive company culture within your business?',
  'Describe a successful social media marketing campaign for your business.',
  'Share a habit that has improved your business communication skills.',
  "What's your favorite business-related app on your smartphone?",
  'How do you approach market research for a new product or service?',
  'Describe a memorable customer testimonial or review.',
  'Share a resource that has helped you improve your leadership skills.',
  "What's your favorite business-related TED Talk or webinar?",
  'How do you incorporate sustainability practices into your business?',
  'Describe a creative promotional offer or discount you implemented.',
  "Share a business challenge you're currently facing and seeking solutions for.",
  "What's your favorite business-related podcast episode?",
  'How do you approach customer service to ensure customer satisfaction?',
  'Describe a time when you had to rebrand your business and the results.',
  'Share a lesson you learned from a business competitor.',
  "What's your favorite business-related social media platform?",
  'How do you stay ethical and transparent in your business practices?',
  'Describe a successful email marketing campaign for your business.',
  'Share a business goal you have for the next year.',
  "What's your favorite strategy for generating leads in your business?",
  'How do you handle imposter syndrome in your entrepreneurial journey?',
  'Describe a successful content marketing campaign for your business.',
  'Share a lesson you learned from a business mentor.',
  "What's your favorite business-related YouTube channel?",
  'How do you approach decision-making in your business?',
  'Describe a time when you had to overcome a legal challenge in your business.',
  'Share a valuable lesson you learned from a business workshop or seminar.',
  "What's your favorite business-related book cover design?",
  'How do you handle burnout and stress in your business?',
  'Describe a successful influencer marketing collaboration for your business.',
  'Share a business-related quote that resonates with you.',
  "What's your favorite business-related LinkedIn group or community?",
  'How do you approach employee recognition and appreciation in your business?',
  'Describe a successful crowdfunding campaign for your business.',
  'Share a lesson you learned from a business-related documentary.',
  "What's your favorite business-related online course?",
  'How do you approach customer feedback to improve your products or services?',
  'Describe a successful affiliate marketing partnership for your business.',
  'Share a business challenge you overcame through innovative solutions.',
  "What's your favorite business-related Instagram account?",
  'How do you incorporate diversity and inclusion practices into your business?',
  'Describe a successful product launch event for your business.',
  'Share a lesson you learned from a business-related podcast episode.',
  "What's your favorite business-related Twitter account?",
  'How do you approach goal setting and achievement in your business?',
  'Describe a successful guerrilla marketing campaign for your business.',
  'Share a valuable lesson you learned from a business-related workshop.',
  "What's your favorite business-related Facebook group or page?",
  'How do you approach business expansion into new markets?',
  'Describe a successful public relations campaign for your business.',
  'Share a lesson you learned from a business-related keynote speaker.',
  "What's your favorite business-related subreddit or forum?",
  'How do you approach crisis management in your business?',
  'Describe a successful joint venture partnership for your business.',
  'Share a lesson you learned from a business-related panel discussion.',
  "What's your favorite business-related Pinterest board?",
  'How do you approach digital marketing to reach a wider audience?',
  'Describe a successful guerrilla marketing tactic you used for your business.',
  'Share a lesson you learned from a business-related case study.',
  "What's your favorite business-related Medium publication?",
  'How do you approach business innovation to stay ahead in your industry?',
  'Describe a successful referral marketing campaign for your business.',
  'Share a lesson you learned from a business-related blog post.',
  "What's your favorite business-related Quora topic?",
  'How do you approach business partnerships for mutual growth?',
  'Describe a successful influencer collaboration for your business.',
  'Share a lesson you learned from a business-related thought leader.',
  "What's your favorite business-related industry conference?",
  'How do you approach customer engagement through social media?',
  'Describe a successful product endorsement partnership for your business.',
  'Share a lesson you learned from a business-related case analysis.',
  "What's your favorite business-related online magazine?",
  'How do you approach business sustainability and eco-friendly practices?',
  'Describe a successful event sponsorship partnership for your business.',
  'Share a lesson you learned from a business-related research paper.',
  "What's your favorite business-related LinkedIn article?",
  'How do you approach business growth through strategic alliances?',
  'Describe a successful content collaboration with another business.',
  'Share a lesson you learned from a business-related whitepaper.',
  "What's your favorite business-related TEDx talk?",
  'How do you approach customer loyalty programs for your business?',
  'Describe a successful cause marketing campaign for your business.',
  'Share a lesson you learned from a business-related market report.',
  "What's your favorite business-related Harvard Business Review article?",
  'How do you approach business differentiation to stand out in the market?',
  'Describe a successful social responsibility initiative for your business.',
  'Share a lesson you learned from a business-related industry publication.',
  "What's your favorite business-related Fast Company article?",
  'How do you approach business agility to adapt to changing market needs?',
  'Describe a successful collaboration with a nonprofit organization.',
  'Share a lesson you learned from a business-related McKinsey report.',
  "What's your favorite business-related Forbes article?",
  'How do you approach customer satisfaction surveys for your business?',
  'Describe a successful collaboration with a government agency or initiative.',
  'Share a lesson you learned from a business-related Deloitte report.',
  "What's your favorite business-related Bloomberg article?",
  'How do you approach product innovation to meet customer demands?',
  'Describe a successful collaboration with an educational institution.',
  'Share a lesson you learned from a business-related Gartner report.',
  "What's your favorite business-related Wall Street Journal article?",
  'How do you approach business reinvention to stay relevant in the industry?',
  'Describe a successful collaboration with a cultural organization.',
  'Share a lesson you learned from a business-related Accenture report.',
  "What's your favorite business-related Inc. article?",
  'How do you approach business modernization to keep up with technology?',
  'Describe a successful collaboration with a local community group.',
  'Share a lesson you learned from a business-related Nielsen report.',
  "What's your favorite business-related Entrepreneur article?",
  'How do you approach business transformation for long-term sustainability?',
  'Describe a successful collaboration with an environmental organization.',
  'Share a lesson you learned from a business-related Pew Research report.',
  "What's your favorite business-related Business Insider article?",
  'How do you approach business optimization for improved efficiency?',
  'Describe a successful collaboration with a health and wellness organization.',
  'Share a lesson you learned from a business-related World Economic Forum report.',
  "What's your favorite business-related TechCrunch article?",
  'How do you approach business integration after a merger or acquisition?',
  'Describe a successful collaboration with a humanitarian organization.',
  'Share a lesson you learned from a business-related United Nations report.',
  "What's your favorite business-related Wired article?",
  'How do you approach business diversification into new product lines?',
  'Describe a successful collaboration with a scientific research organization.',
  'Share a lesson you learned from a business-related Harvard University report.',
  "What's your favorite business-related New York Times article?",
  'How do you approach business consolidation after rapid expansion?',
  'Describe a successful collaboration with a charitable foundation.',
  'Share a lesson you learned from a business-related Stanford University report.',
  "What's your favorite business-related BBC article?",
  'How do you approach business localization for different cultural markets?',
  'Describe a successful collaboration with a technology research organization.',
  'Share a lesson you learned from a business-related Oxford University report.',
  "What's your favorite business-related The Guardian article?",
  'How do you approach business globalization for international markets?',
  'Describe a successful collaboration with a renewable energy organization.',
  'Share a lesson you learned from a business-related Cambridge University report.',
  "What's your favorite business-related NPR article?",
  'How do you approach business ethics and social responsibility?',
  'Describe a successful collaboration with a wildlife conservation organization.',
  'Share a lesson you learned from a business-related Smithsonian Institution report.',
  "What's your favorite business-related National Geographic article?",
  'How do you approach business innovation in the digital age?',
  'Describe a successful collaboration with an art and culture organization.',
  'Share a lesson you learned from a business-related Getty Museum report.',
  "What's your favorite business-related TED article?",
  'How do you approach business sustainability in the face of climate change?',
  'Describe a successful collaboration with a historical preservation organization.',
  'Share a lesson you learned from a business-related Louvre Museum report.',
  "What's your favorite business-related Google article?",
  'How do you approach business transformation in response to technological advancements?',
  'Describe a successful collaboration with a space exploration organization.',
  'Share a lesson you learned from a business-related NASA report.',
  "What's your favorite business-related Wikipedia article?",
  'How do you approach business innovation for a sustainable future?',
  'Describe a successful collaboration with a humanitarian aid organization.',
  'Share a lesson you learned from a business-related Red Cross report.',
  "What's your favorite business-related UNESCO article?",
  'How do you approach business optimization for a greener planet?',
  'Describe a successful collaboration with a wildlife preservation organization.',
  'Share a lesson you learned from a business-related WWF report.',
  "What's your favorite business-related Greenpeace article?",
  'How do you approach business localization for diverse global markets?',
  'Describe a successful collaboration with a human rights organization.',
  'Share a lesson you learned from a business-related Amnesty International report.',
  "What's your favorite business-related Oxfam article?",
  'How do you approach business globalization for a sustainable future?',
  'Describe a successful collaboration with a global health organization.',
  'Share a lesson you learned from a business-related World Health Organization report.',
  "What's your favorite business-related UNICEF article?",
  'How do you approach business ethics and social responsibility for a better world?',
  'Describe a successful collaboration with a global education organization.',
  'Share a lesson you learned from a business-related UNESCO report.',
  "What's your favorite business-related Save the Children article?",
  'How do you approach business innovation for the betterment of society?',
  'Describe a successful collaboration with a global environmental organization.',
  'Share a lesson you learned from a business-related Greenpeace International report.',
  "What's your favorite business-related Amnesty International article?",
  'How do you approach business optimization for the welfare of all?',
  'Describe a successful collaboration with a global poverty alleviation organization.',
  'Share a lesson you learned from a business-related Oxfam International report.',
  "What's your favorite business-related UNICEF International article?",
  'How do you approach business globalization for the well-being of humanity?',
  'Describe a successful collaboration with a global healthcare organization.',
  'Share a lesson you learned from a business-related World Health Organization International report.',
  "What's your favorite business-related United Nations International article?",
  'How do you approach business ethics and social responsibility for the good of the planet?',
  'Describe a successful collaboration with a global environmental preservation organization.',
  'Share a lesson you learned from a business-related Earth Day Network report.',
  "What's your favorite business-related Sierra Club article?",
  'How do you approach business innovation for the conservation of nature?',
  'Describe a successful collaboration with a global animal welfare organization.',
  'Share a lesson you learned from a business-related World Animal Protection report.',
  "What's your favorite business-related National Audubon Society article?",
  'How do you approach business optimization for the protection of wildlife?',
  'Describe a successful collaboration with a global cultural heritage organization.',
  'Share a lesson you learned from a business-related UNESCO World Heritage Centre report.',
  "What's your favorite business-related World Monuments Fund article?",
  'How do you approach business globalization for the preservation of cultural heritage?',
  'Describe a successful collaboration with a global arts and culture organization.',
  'Share a lesson you learned from a business-related United Nations Educational, Scientific and Cultural Organization report.',
  "What's your favorite business-related Smithsonian Institution article?",
  'How do you approach business ethics and social responsibility for the preservation of cultural diversity?',
  'Describe a successful collaboration with a global cultural diversity organization.',
  'Share a lesson you learned from a business-related Cultural Survival report.',
  "What's your favorite business-related Survival International article?",
  'How do you approach business innovation for the preservation of indigenous cultures?',
  'Describe a successful collaboration with a global indigenous rights organization.',
  "Share a lesson you learned from a business-related Indigenous Peoples' Rights International report.",
  "What's your favorite business-related Amazon Watch article?",
  'How do you approach business optimization for the protection of indigenous lands?',
  'Describe a successful collaboration with a global indigenous land rights organization.',
  'Share a lesson you learned from a business-related Rainforest Foundation report.',
  "What's your favorite business-related Cultural Survival article?",
  "How do you approach business globalization for the preservation of indigenous peoples' rights?",
  "Describe a successful collaboration with a global women's rights organization.",
  'Share a lesson you learned from a business-related UN Women report.',
  "What's your favorite business-related Women for Women International article?",
  "How do you approach business ethics and social responsibility for the advancement of women's rights?",
  'Describe a successful collaboration with a global human rights organization.',
  'Share a lesson you learned from a business-related Human Rights Watch report.',
  "What's your favorite business-related Amnesty International Women's Rights article?",
  'How do you approach business innovation for the promotion of gender equality?',
  'Describe a successful collaboration with a global LGBTQ+ rights organization.',
  'Share a lesson you learned from a business-related Human Rights Campaign report.',
  "What's your favorite business-related International Lesbian, Gay, Bisexual, Trans and Intersex Association article?",
  'How do you approach business optimization for LGBTQ+ rights and inclusion?',
  'Describe a successful collaboration with a global disability rights organization.',
  'Share a lesson you learned from a business-related World Institute on Disability report.',
  "What's your favorite business-related Disabled Peoples' International article?",
  'How do you approach business globalization for the promotion of disability rights?',
  'Describe a successful collaboration with a global mental health organization.',
  'Share a lesson you learned from a business-related World Federation for Mental Health report.',
  "What's your favorite business-related Mental Health America article?",
  'How do you approach business ethics and social responsibility for mental health awareness?',
  'Describe a successful collaboration with a global education access organization.',
  'Share a lesson you learned from a business-related Malala Fund report.',
  "What's your favorite business-related Save the Children Education article?",
  'How do you approach business innovation for improving educational access?',
  'Describe a successful collaboration with a global healthcare access organization.',
  'Share a lesson you learned from a business-related Doctors Without Borders report.',
  "What's your favorite business-related Partners In Health article?",
  'How do you approach business optimization for healthcare access and affordability?',
  'Describe a successful collaboration with a global clean energy organization.',
  'Share a lesson you learned from a business-related Sierra Club Clean Energy report.',
  "What's your favorite business-related Clean Energy for America article?",
  'How do you approach business globalization for clean and renewable energy solutions?',
  'Describe a successful collaboration with a global environmental conservation organization.',
  'Share a lesson you learned from a business-related Nature Conservancy report.',
  "What's your favorite business-related Conservation International article?",
  'How do you approach business ethics and social responsibility for environmental conservation?',
  'Describe a successful collaboration with a global climate change organization.',
  'Share a lesson you learned from a business-related Intergovernmental Panel on Climate Change report.',
  "What's your favorite business-related Climate Reality Project article?",
  'How do you approach business innovation for climate change mitigation?',
  'Describe a successful collaboration with a global wildlife conservation organization.',
  'Share a lesson you learned from a business-related World Wildlife Fund report.',
  "What's your favorite business-related Wildlife Conservation Society article?",
  'How do you approach business optimization for wildlife conservation and protection?',
  'Describe a successful collaboration with a global human rights and environmental organization.',
  'Share a lesson you learned from a business-related EarthRights International report.',
  "What's your favorite business-related Environmental Investigation Agency article?",
  'How do you approach business globalization for the intersection of human rights and environmental protection?',
  'Describe a successful collaboration with a global social justice organization.',
  'Share a lesson you learned from a business-related Oxfam International report.',
  "What's your favorite business-related Anti-Slavery International article?",
  'How do you approach business ethics and social responsibility for social justice?',
  'Describe a successful collaboration with a global anti-corruption organization.',
  'Share a lesson you learned from a business-related Transparency International report.',
  "What's your favorite business-related Global Witness article?",
  'How do you approach business innovation for combating corruption?',
  'Describe a successful collaboration with a global democracy and governance organization.',
  'Share a lesson you learned from a business-related International Institute for Democracy and Electoral Assistance report.',
  "What's your favorite business-related National Democratic Institute article?",
  'How do you approach business optimization for strengthening democracy and governance?',
  'Describe a successful collaboration with a global peacebuilding organization.',
  'Share a lesson you learned from a business-related International Alert report.',
  "What's your favorite business-related Alliance for Peacebuilding article?",
  'How do you approach business globalization for promoting peace and conflict resolution?',
  'Describe a successful collaboration with a global disaster response organization.',
  'Share a lesson you learned from a business-related International Federation of Red Cross and Red Crescent Societies report.',
  "What's your favorite business-related CARE International article?",
  'How do you approach business ethics and social responsibility for disaster response and relief?',
  'Describe a successful collaboration with a global humanitarian aid organization.',
  'Share a lesson you learned from a business-related Médecins Sans Frontières report.',
  "What's your favorite business-related Humanitarian Coalition article?",
  'How do you approach business innovation for humanitarian aid and crisis response?',
  'Describe a successful collaboration with a global public health organization.',
  'Share a lesson you learned from a business-related World Health Organization report.',
  "What's your favorite business-related Médecins Sans Frontières article?",
  'How do you approach business optimization for public health initiatives?',
  'Describe a successful collaboration with a global education access organization.',
  'Share a lesson you learned from a business-related Malala Fund report.',
  "What's your favorite business-related Save the Children Education article?",
  'How do you approach business innovation for improving educational access?',
  'Describe a successful collaboration with a global healthcare access organization.',
  'Share a lesson you learned from a business-related Doctors Without Borders report.',
  "What's your favorite business-related Partners In Health article?",
  'How do you approach business optimization for healthcare access and affordability?',
  'Describe a successful collaboration with a global clean energy organization.',
  'Share a lesson you learned from a business-related Sierra Club Clean Energy report.',
  "What's your favorite business-related Clean Energy for America article?",
  'How do you approach business globalization for clean and renewable energy solutions?',
  'Describe a successful collaboration with a global environmental conservation organization.',
  'Share a lesson you learned from a business-related Nature Conservancy report.',
  "What's your favorite business-related Conservation International article?",
  'How do you approach business ethics and social responsibility for environmental conservation?',
  'Describe a successful collaboration with a global climate change organization.',
  'Share a lesson you learned from a business-related Intergovernmental Panel on Climate Change report.',
  "What's your favorite business-related Climate Reality Project article?",
  'How do you approach business innovation for climate change mitigation?',
  'Describe a successful collaboration with a global wildlife conservation organization.',
  'Share a lesson you learned from a business-related World Wildlife Fund report.',
  "What's your favorite business-related Wildlife Conservation Society article?",
  'How do you approach business optimization for wildlife conservation and protection?',
  'Describe a successful collaboration with a global human rights and environmental organization.',
  'Share a lesson you learned from a business-related EarthRights International report.',
  "What's your favorite business-related Environmental Investigation Agency article?",
  'How do you approach business globalization for the intersection of human rights and environmental protection?',
  'Describe a successful collaboration with a global social justice organization.',
  'Share a lesson you learned from a business-related Oxfam International report.',
  "What's your favorite business-related Anti-Slavery International article?",
  'How do you approach business ethics and social responsibility for social justice?',
  'Describe a successful collaboration with a global anti-corruption organization.',
  'Share a lesson you learned from a business-related Transparency International report.',
  "What's your favorite business-related Global Witness article?",
  'How do you approach business innovation for combating corruption?',
  'Describe a successful collaboration with a global democracy and governance organization.',
  'Share a lesson you learned from a business-related International Institute for Democracy and Electoral Assistance report.',
  "What's your favorite business-related National Democratic Institute article?",
  'How do you approach business optimization for strengthening democracy and governance?',
  'Describe a successful collaboration with a global peacebuilding organization.',
  'Share a lesson you learned from a business-related International Alert report.',
  "What's your favorite business-related Alliance for Peacebuilding article?",
  'How do you approach business globalization for promoting peace and conflict resolution?',
  'Describe a successful collaboration with a global disaster response organization.',
  'Share a lesson you learned from a business-related International Federation of Red Cross and Red Crescent Societies report.',
  "What's your favorite business-related CARE International article?",
  'How do you approach business ethics and social responsibility for disaster response and relief?',
  'Describe a successful collaboration with a global humanitarian aid organization.',
  'Share a lesson you learned from a business-related Médecins Sans Frontières report.',
  "What's your favorite business-related Humanitarian Coalition article?",
  'How do you approach business innovation for humanitarian aid and crisis response?',
  'Describe a successful collaboration with a global public health organization.',
  'Share a lesson you learned from a business-related World Health Organization report.',
  "What's your favorite business-related Médecins Sans Frontières article?",
  'How do you approach business optimization for public health initiatives?',
  'Describe a successful collaboration with a global education access organization.',
  'Share a lesson you learned from a business-related Malala Fund report.',
  "What's your favorite business-related Save the Children Education article?",
  'How do you approach business innovation for improving educational access?',
  'Describe a successful collaboration with a global healthcare access organization.',
  'Share a lesson you learned from a business-related Doctors Without Borders report.',
  "What's your favorite business-related Partners In Health article?",
  'How do you approach business optimization for healthcare access and affordability?',
  'Describe a successful collaboration with a global clean energy organization.',
  'Share a lesson you learned from a business-related Sierra Club Clean Energy report.',
  "What's your favorite business-related Clean Energy for America article?",
  'How do you approach business globalization for clean and renewable energy solutions?',
  'Describe a successful collaboration with a global environmental conservation organization.',
  'Share a lesson you learned from a business-related Nature Conservancy report.',
  "What's your favorite business-related Conservation International article?",
  'How do you approach business ethics and social responsibility for environmental conservation?',
  'Describe a successful collaboration with a global climate change organization.',
  'Share a lesson you learned from a business-related Intergovernmental Panel on Climate Change report.',
  "What's your favorite business-related Climate Reality Project article?",
  'How do you approach business innovation for climate change mitigation?',
  'Describe a successful collaboration with a global wildlife conservation organization.',
  'Share a lesson you learned from a business-related World Wildlife Fund report.',
  "What's your favorite business-related Wildlife Conservation Society article?",
  'How do you approach business optimization for wildlife conservation and protection?',
  'Describe a successful collaboration with a global human rights and environmental organization.',
  'Share a lesson you learned from a business-related EarthRights International report.',
  "What's your favorite business-related Environmental Investigation Agency article?",
  'How do you approach business globalization for the intersection of human rights and environmental protection?',
  'Describe a successful collaboration with a global social justice organization.',
  'Share a lesson you learned from a business-related Oxfam International report.',
  "What's your favorite business-related Anti-Slavery International article?",
  'How do you approach business ethics and social responsibility for social justice?',
  'Describe a successful collaboration with a global anti-corruption organization.',
  'Share a lesson you learned from a business-related Transparency International report.',
  "What's your favorite business-related Global Witness article?",
  'How do you approach business innovation for combating corruption?',
  'Describe a successful collaboration with a global democracy and governance organization.',
  'Share a lesson you learned from a business-related International Institute for Democracy and Electoral Assistance report.',
  "What's your favorite business-related National Democratic Institute article?",
  'How do you approach business optimization for strengthening democracy and governance?',
  'Describe a successful collaboration with a global peacebuilding organization.',
  'Share a lesson you learned from a business-related International Alert report.',
  "What's your favorite business-related Alliance for Peacebuilding article?",
  'How do you approach business globalization for promoting peace and conflict resolution?',
  'Describe a successful collaboration with a global disaster response organization.',
  'Share a lesson you learned from a business-related International Federation of Red Cross and Red Crescent Societies report.',
  "What's your favorite business-related CARE International article?",
  'How do you approach business ethics and social responsibility for disaster response and relief?',
  'Describe a successful collaboration with a global humanitarian aid organization.',
  'Share a lesson you learned from a business-related Médecins Sans Frontières report.',
  "What's your favorite business-related Humanitarian Coalition article?",
  'How do you approach business innovation for humanitarian aid and crisis response?',
  'Describe a successful collaboration with a global public health organization.',
  'Share a lesson you learned from a business-related World Health Organization report.',
  "What's your favorite business-related Médecins Sans Frontières article?",
  'How do you approach business optimization for public health initiatives?',
  'Describe a successful collaboration with a global education access organization.',
  'Share a lesson you learned from a business-related Malala Fund report.',
  "What's your favorite business-related Save the Children Education article?",
  'How do you approach business innovation for improving educational access?',
  'Describe a successful collaboration with a global healthcare access organization.',
  'Share a lesson you learned from a business-related Doctors Without Borders report.',
  "What's your favorite business-related Partners In Health article?",
  'How do you approach business optimization for healthcare access and affordability?',
  'Describe a successful collaboration with a global clean energy organization.',
  'Share a lesson you learned from a business-related Sierra Club Clean Energy report.',
  "What's your favorite business-related Clean Energy for America article?",
  'How do you approach business globalization for clean and renewable energy solutions?',
  'Describe a successful collaboration with a global environmental conservation organization.',
  'Share a lesson you learned from a business-related Nature Conservancy report.',
  "What's your favorite business-related Conservation International article?",
  'How do you approach business ethics and social responsibility for environmental conservation?',
  'Describe a successful collaboration with a global climate change organization.',
  'Share a lesson you learned from a business-related Intergovernmental Panel on Climate Change report.',
  "What's your favorite business-related Climate Reality Project article?",
  'How do you approach business innovation for climate change mitigation?',
  'Describe a successful collaboration with a global wildlife conservation organization.',
  'Share a lesson you learned from a business-related World Wildlife Fund report.',
  "What's your favorite business-related Wildlife Conservation Society article?",
  'How do you approach business optimization for wildlife conservation and protection?',
  'Describe a successful collaboration with a global human rights and environmental organization.',
  'Share a lesson you learned from a business-related EarthRights International report.',
  "What's your favorite business-related Environmental Investigation Agency article?",
  'How do you approach business globalization for the intersection of human rights and environmental protection?',
  'Describe a successful collaboration with a global social justice organization.',
  'Share a lesson you learned from a business-related Oxfam International report.',
  "What's your favorite business-related Anti-Slavery International article?",
  'How do you approach business ethics and social responsibility for social justice?',
  'Describe a successful collaboration with a global anti-corruption organization.',
  'Share a lesson you learned from a business-related Transparency International report.',
  "What's your favorite business-related Global Witness article?",
  'How do you approach business innovation for combating corruption?',
  'Describe a successful collaboration with a global democracy and governance organization.',
  'Share a lesson you learned from a business-related International Institute for Democracy and Electoral Assistance report.',
  "What's your favorite business-related National Democratic Institute article?",
  'How do you approach business optimization for strengthening democracy and governance?',
  'Describe a successful collaboration with a global peacebuilding organization.',
  'Share a lesson you learned from a business-related International Alert report.',
  "What's your favorite business-related Alliance for Peacebuilding article?",
  'How do you approach business globalization for promoting peace and conflict resolution?',
  'Describe a successful collaboration with a global disaster response organization.',
  'Share a lesson you learned from a business-related International Federation of Red Cross and Red Crescent Societies report.',
  "What's your favorite business-related CARE International article?",
  'How do you approach business ethics and social responsibility for disaster response and relief?',
  'Describe a successful collaboration with a global humanitarian aid organization.',
  'Share a lesson you learned from a business-related Médecins Sans Frontières report.',
  "What's your favorite business-related Humanitarian Coalition article?",
  'How do you approach business innovation for humanitarian aid and crisis response?',
  'Describe a successful collaboration with a global public health organization.',
  'Share a lesson you learned from a business-related World Health Organization report.',
  "What's your favorite business-related Médecins Sans Frontières article?",
  'How do you approach business optimization for public health initiatives?',
  'Describe a successful collaboration with a global education access organization.',
  'Share a lesson you learned from a business-related Malala Fund report.',
  "What's your favorite business-related Save the Children Education article?",
  'How do you approach business innovation for improving educational access?',
  'Describe a successful collaboration with a global healthcare access organization.',
];
