export const businessQuestions = [
  'What inspired you to start your own business?',
  'How do you stay motivated during challenging times in your business?',
  "What's the best business advice you've ever received?",
  'Share a book that has influenced your entrepreneurial journey.',
  "What's the most important skill for an entrepreneur to have?",
  'How do you balance work and personal life as an entrepreneur?',
  "What's the biggest lesson you've learned from a business failure?",
  'How do you come up with new business ideas?',
  'Share a productivity tip that helps you stay efficient in your work.',
  'How do you handle stress in your business?',
  'Who is your business idol, and why?',
  "What's the key to successful networking in the business world?",
  'Share a memorable moment from your entrepreneurial journey.',
  'How do you handle disagreements with business partners or clients?',
  "What's your favorite business-related podcast or YouTube channel?",
  'Describe your ideal workplace environment for maximum productivity.',
  "What's the most challenging aspect of running a business for you?",
  "Share a business goal you've achieved recently and how you did it.",
  "What's the impact you want your business to make in the world?",
  'How do you approach market research for a new business idea?',
  "What's your favorite business-related quote?",
  'Share a habit that has contributed to your business success.',
  'How do you adapt to changing market trends in your industry?',
  'Describe your most innovative business idea.',
  "What's your favorite tool or software for business management?",
  'Share a piece of advice you wish you had known when you started your business.',
  'How do you prioritize tasks and projects in your business?',
  "What's your favorite aspect of entrepreneurship?",
  'Describe a challenge you faced and overcame in your business.',
  'Share a resource (book, course, website) that has helped you in your business journey.',
  "What's your favorite way to celebrate business milestones?",
  'How do you build a strong team for your business?',
  'Share a marketing strategy that worked exceptionally well for your business.',
  "What's the most rewarding part of being an entrepreneur?",
  'How do you stay updated with the latest industry trends?',
  'Describe a mentorship experience that positively impacted your business.',
  'Share a lesson you learned from a business setback.',
  "What's your favorite business-related event or conference?",
  'How do you maintain a healthy work-life balance as an entrepreneur?',
  'Describe a creative marketing campaign you executed for your business.',
  "What's your favorite business-related documentary or movie?",
  "Share a goal you're currently working towards in your business.",
  'How do you stay organized with your business tasks and projects?',
  "What's your approach to time management in your business?",
  'Describe a collaboration or partnership that benefited your business.',
  'Share a piece of technology that has revolutionized your business operations.',
  "What's your favorite strategy for customer retention?",
  'How do you handle negative feedback or criticism about your business?',
  'Describe a project or product launch that was particularly successful.',
  'Share a story of a customer or client who had a significant impact on your business.',
  "What's your favorite business-related blog or website?",
  'How do you stay creative and innovative in your business ideas?',
  'Describe a time when you had to pivot your business strategy and how it turned out.',
  'Share a valuable lesson you learned from a mentor or advisor.',
  "What's your favorite aspect of your business culture?",
  'How do you handle setbacks and failures in your business?',
  "Describe a partnership or collaboration that didn't work out and the lessons learned.",
  'Share a personal habit that has positively influenced your business productivity.',
  "What's your approach to building a strong brand for your business?",
  'How do you foster a positive company culture within your business?',
  'Describe a successful social media marketing campaign for your business.',
  'Share a habit that has improved your business communication skills.',
  "What's your favorite business-related app on your smartphone?",
  'How do you approach market research for a new product or service?',
  'Describe a memorable customer testimonial or review.',
  'Share a resource that has helped you improve your leadership skills.',
  "What's your favorite business-related TED Talk or webinar?",
  'How do you incorporate sustainability practices into your business?',
  'Describe a creative promotional offer or discount you implemented.',
  "Share a business challenge you're currently facing and seeking solutions for.",
  "What's your favorite business-related podcast episode?",
  'How do you approach customer service to ensure customer satisfaction?',
  'Describe a time when you had to rebrand your business and the results.',
  'Share a lesson you learned from a business competitor.',
  "What's your favorite business-related social media platform?",
  'How do you stay ethical and transparent in your business practices?',
  'Describe a successful email marketing campaign for your business.',
  'Share a business goal you have for the next year.',
  "What's your favorite strategy for generating leads in your business?",
  'How do you handle imposter syndrome in your entrepreneurial journey?',
  'Describe a successful content marketing campaign for your business.',
  'Share a lesson you learned from a business mentor.',
  "What's your favorite business-related YouTube channel?",
  'How do you approach decision-making in your business?',
  'Describe a time when you had to overcome a legal challenge in your business.',
  'Share a valuable lesson you learned from a business workshop or seminar.',
  "What's your favorite business-related book cover design?",
  'How do you handle burnout and stress in your business?',
  'Describe a successful influencer marketing collaboration for your business.',
  'Share a business-related quote that resonates with you.',
  "What's your favorite business-related LinkedIn group or community?",
  'How do you approach employee recognition and appreciation in your business?',
  'Describe a successful crowdfunding campaign for your business.',
  'Share a lesson you learned from a business-related documentary.',
  "What's your favorite business-related online course?",
  'How do you approach customer feedback to improve your products or services?',
  'Describe a successful affiliate marketing partnership for your business.',
  'Share a business challenge you overcame through innovative solutions.',
  "What's your favorite business-related Instagram account?",
  'How do you incorporate diversity and inclusion practices into your business?',
  'Describe a successful product launch event for your business.',
  'Share a lesson you learned from a business-related podcast episode.',
  "What's your favorite business-related Twitter account?",
  'How do you approach goal setting and achievement in your business?',
  'Describe a successful guerrilla marketing campaign for your business.',
  'Share a valuable lesson you learned from a business-related workshop.',
  "What's your favorite business-related Facebook group or page?",
  'How do you approach business expansion into new markets?',
  'Describe a successful public relations campaign for your business.',
  'Share a lesson you learned from a business-related keynote speaker.',
  "What's your favorite business-related subreddit or forum?",
  'How do you approach crisis management in your business?',
  'Describe a successful joint venture partnership for your business.',
  'Share a lesson you learned from a business-related panel discussion.',
  "What's your favorite business-related Pinterest board?",
  'How do you approach digital marketing to reach a wider audience?',
  'Describe a successful guerrilla marketing tactic you used for your business.',
  'Share a lesson you learned from a business-related case study.',
  "What's your favorite business-related Medium publication?",
  'How do you approach business innovation to stay ahead in your industry?',
  'Describe a successful referral marketing campaign for your business.',
  'Share a lesson you learned from a business-related blog post.',
  "What's your favorite business-related Quora topic?",
  'How do you approach business partnerships for mutual growth?',
  'Describe a successful influencer collaboration for your business.',
  'Share a lesson you learned from a business-related thought leader.',
  "What's your favorite business-related industry conference?",
  'How do you approach customer engagement through social media?',
  'Describe a successful product endorsement partnership for your business.',
  'Share a lesson you learned from a business-related case analysis.',
  "What's your favorite business-related online magazine?",
  'How do you approach business sustainability and eco-friendly practices?',
  'Describe a successful event sponsorship partnership for your business.',
  'Share a lesson you learned from a business-related research paper.',
  "What's your favorite business-related LinkedIn article?",
  'How do you approach business growth through strategic alliances?',
  'Describe a successful content collaboration with another business.',
  'Share a lesson you learned from a business-related whitepaper.',
  "What's your favorite business-related TEDx talk?",
  'How do you approach customer loyalty programs for your business?',
  'Describe a successful cause marketing campaign for your business.',
  'Share a lesson you learned from a business-related market report.',
  "What's your favorite business-related Harvard Business Review article?",
  'How do you approach business differentiation to stand out in the market?',
  'Describe a successful social responsibility initiative for your business.',
  'Share a lesson you learned from a business-related industry publication.',
  "What's your favorite business-related Fast Company article?",
  'How do you approach business agility to adapt to changing market needs?',
  'Describe a successful collaboration with a nonprofit organization.',
  'Share a lesson you learned from a business-related McKinsey report.',
  "What's your favorite business-related Forbes article?",
  'How do you approach customer satisfaction surveys for your business?',
  'Describe a successful collaboration with a government agency or initiative.',
  'Share a lesson you learned from a business-related Deloitte report.',
  "What's your favorite business-related Bloomberg article?",
  'How do you approach product innovation to meet customer demands?',
  'Describe a successful collaboration with an educational institution.',
  'Share a lesson you learned from a business-related Gartner report.',
  "What's your favorite business-related Wall Street Journal article?",
  'How do you approach business reinvention to stay relevant in the industry?',
  'Describe a successful collaboration with a cultural organization.',
  'Share a lesson you learned from a business-related Accenture report.',
  "What's your favorite business-related Inc. article?",
  'How do you approach business modernization to keep up with technology?',
  'Describe a successful collaboration with a local community group.',
  'Share a lesson you learned from a business-related Nielsen report.',
  "What's your favorite business-related Entrepreneur article?",
  'How do you approach business transformation for long-term sustainability?',
  'Describe a successful collaboration with an environmental organization.',
  'Share a lesson you learned from a business-related Pew Research report.',
  "What's your favorite business-related Business Insider article?",
  'How do you approach business optimization for improved efficiency?',
  'Describe a successful collaboration with a health and wellness organization.',
  'Share a lesson you learned from a business-related World Economic Forum report.',
  "What's your favorite business-related TechCrunch article?",
  'How do you approach business integration after a merger or acquisition?',
  'Describe a successful collaboration with a humanitarian organization.',
  'Share a lesson you learned from a business-related United Nations report.',
  "What's your favorite business-related Wired article?",
  'How do you approach business diversification into new product lines?',
  'Describe a successful collaboration with a scientific research organization.',
  'Share a lesson you learned from a business-related Harvard University report.',
  "What's your favorite business-related New York Times article?",
  'How do you approach business consolidation after rapid expansion?',
  'Describe a successful collaboration with a charitable foundation.',
  'Share a lesson you learned from a business-related Stanford University report.',
  "What's your favorite business-related BBC article?",
  'How do you approach business localization for different cultural markets?',
  'Describe a successful collaboration with a technology research organization.',
  'Share a lesson you learned from a business-related Oxford University report.',
  "What's your favorite business-related The Guardian article?",
  'How do you approach business globalization for international markets?',
  'Describe a successful collaboration with a renewable energy organization.',
  'Share a lesson you learned from a business-related Cambridge University report.',
  "What's your favorite business-related NPR article?",
  'How do you approach business ethics and social responsibility?',
  'Describe a successful collaboration with a wildlife conservation organization.',
  'Share a lesson you learned from a business-related Smithsonian Institution report.',
  "What's your favorite business-related National Geographic article?",
  'How do you approach business innovation in the digital age?',
  'Describe a successful collaboration with an art and culture organization.',
  'Share a lesson you learned from a business-related Getty Museum report.',
  "What's your favorite business-related TED article?",
  'How do you approach business sustainability in the face of climate change?',
  'Describe a successful collaboration with a historical preservation organization.',
  'Share a lesson you learned from a business-related Louvre Museum report.',
  "What's your favorite business-related Google article?",
  'How do you approach business transformation in response to technological advancements?',
  'Describe a successful collaboration with a space exploration organization.',
  'Share a lesson you learned from a business-related NASA report.',
  "What's your favorite business-related Wikipedia article?",
  'How do you approach business innovation for a sustainable future?',
  'Describe a successful collaboration with a humanitarian aid organization.',
  'Share a lesson you learned from a business-related Red Cross report.',
  "What's your favorite business-related UNESCO article?",
  'How do you approach business optimization for a greener planet?',
  'Describe a successful collaboration with a wildlife preservation organization.',
  'Share a lesson you learned from a business-related WWF report.',
  "What's your favorite business-related Greenpeace article?",
  'How do you approach business localization for diverse global markets?',
  'Describe a successful collaboration with a human rights organization.',
  'Share a lesson you learned from a business-related Amnesty International report.',
  "What's your favorite business-related Oxfam article?",
  'How do you approach business globalization for a sustainable future?',
  'Describe a successful collaboration with a global health organization.',
  'Share a lesson you learned from a business-related World Health Organization report.',
  "What's your favorite business-related UNICEF article?",
  'How do you approach business ethics and social responsibility for a better world?',
  'Describe a successful collaboration with a global education organization.',
  'Share a lesson you learned from a business-related UNESCO report.',
  "What's your favorite business-related Save the Children article?",
  'How do you approach business innovation for the betterment of society?',
  'Describe a successful collaboration with a global environmental organization.',
  'Share a lesson you learned from a business-related Greenpeace International report.',
  "What's your favorite business-related Amnesty International article?",
  'How do you approach business optimization for the welfare of all?',
  'Describe a successful collaboration with a global poverty alleviation organization.',
  'Share a lesson you learned from a business-related Oxfam International report.',
  "What's your favorite business-related UNICEF International article?",
  'How do you approach business globalization for the well-being of humanity?',
  'Describe a successful collaboration with a global healthcare organization.',
  'Share a lesson you learned from a business-related World Health Organization International report.',
  "What's your favorite business-related United Nations International article?",
  'How do you approach business ethics and social responsibility for the good of the planet?',
  'Describe a successful collaboration with a global environmental preservation organization.',
  'Share a lesson you learned from a business-related Earth Day Network report.',
  "What's your favorite business-related Sierra Club article?",
  'How do you approach business innovation for the conservation of nature?',
  'Describe a successful collaboration with a global animal welfare organization.',
  'Share a lesson you learned from a business-related World Animal Protection report.',
  "What's your favorite business-related National Audubon Society article?",
  'How do you approach business optimization for the protection of wildlife?',
  'Describe a successful collaboration with a global cultural heritage organization.',
  'Share a lesson you learned from a business-related UNESCO World Heritage Centre report.',
  "What's your favorite business-related World Monuments Fund article?",
  'How do you approach business globalization for the preservation of cultural heritage?',
  'Describe a successful collaboration with a global arts and culture organization.',
  'Share a lesson you learned from a business-related United Nations Educational, Scientific and Cultural Organization report.',
  "What's your favorite business-related Smithsonian Institution article?",
  'How do you approach business ethics and social responsibility for the preservation of cultural diversity?',
  'Describe a successful collaboration with a global cultural diversity organization.',
  'Share a lesson you learned from a business-related Cultural Survival report.',
  "What's your favorite business-related Survival International article?",
  'How do you approach business innovation for the preservation of indigenous cultures?',
  'Describe a successful collaboration with a global indigenous rights organization.',
  "Share a lesson you learned from a business-related Indigenous Peoples' Rights International report.",
  "What's your favorite business-related Amazon Watch article?",
  'How do you approach business optimization for the protection of indigenous lands?',
  'Describe a successful collaboration with a global indigenous land rights organization.',
  'Share a lesson you learned from a business-related Rainforest Foundation report.',
  "What's your favorite business-related Cultural Survival article?",
  "How do you approach business globalization for the preservation of indigenous peoples' rights?",
  "Describe a successful collaboration with a global women's rights organization.",
  'Share a lesson you learned from a business-related UN Women report.',
  "What's your favorite business-related Women for Women International article?",
  "How do you approach business ethics and social responsibility for the advancement of women's rights?",
  'Describe a successful collaboration with a global human rights organization.',
  'Share a lesson you learned from a business-related Human Rights Watch report.',
  "What's your favorite business-related Amnesty International Women's Rights article?",
  'How do you approach business innovation for the promotion of gender equality?',
  'Describe a successful collaboration with a global LGBTQ+ rights organization.',
  'Share a lesson you learned from a business-related Human Rights Campaign report.',
  "What's your favorite business-related International Lesbian, Gay, Bisexual, Trans and Intersex Association article?",
  'How do you approach business optimization for LGBTQ+ rights and inclusion?',
  'Describe a successful collaboration with a global disability rights organization.',
  'Share a lesson you learned from a business-related World Institute on Disability report.',
  "What's your favorite business-related Disabled Peoples' International article?",
  'How do you approach business globalization for the promotion of disability rights?',
  'Describe a successful collaboration with a global mental health organization.',
  'Share a lesson you learned from a business-related World Federation for Mental Health report.',
  "What's your favorite business-related Mental Health America article?",
  'How do you approach business ethics and social responsibility for mental health awareness?',
  'Describe a successful collaboration with a global education access organization.',
  'Share a lesson you learned from a business-related Malala Fund report.',
  "What's your favorite business-related Save the Children Education article?",
  'How do you approach business innovation for improving educational access?',
  'Describe a successful collaboration with a global healthcare access organization.',
  'Share a lesson you learned from a business-related Doctors Without Borders report.',
  "What's your favorite business-related Partners In Health article?",
  'How do you approach business optimization for healthcare access and affordability?',
];

export const icebreakerQuestions = [
  "What's the most exciting thing you've done recently?",
  'If you could travel anywhere in the world, where would you go and why?',
  "What's your favorite book/movie/TV show and what do you love about it?",
  'If you had a superpower, what would it be and how would you use it?',
  "What's a skill you've always wanted to learn?",
  "Tell me about a goal you've achieved that you're really proud of.",
  "What's the best piece of advice you've ever received?",
  'If you could have dinner with any historical figure, who would it be and why?',
  "What's a hobby or activity that you enjoy in your free time?",
  "What's your favorite type of cuisine and do you have a favorite dish?",
  'If you could switch lives with someone for a day, who would it be and why?',
  "What's your favorite childhood memory?",
  "Do you have any upcoming plans or events that you're looking forward to?",
  "What's a random fact about yourself that not many people know?",
  'If you could solve any world problem, what would it be and how would you do it?',
  "What's your favorite way to relax and unwind after a busy day?",
  'If you could have any job in the world for one week, what would it be?',
  "What's the most interesting place you've ever visited?",
  "What's a movie or TV show you think everyone should watch and why?",
  'If you could time travel to any era, past or future, where would you go?',
  "What's your go-to karaoke song?",
  'If you could only eat one cuisine for the rest of your life, what would it be?',
  "What's the most beautiful place you've ever seen?",
  'If you could meet any fictional character, who would it be and why?',
  "What's a talent you have that not many people know about?",
  'If you could donate a million dollars to any cause, what would it be?',
  "What's a tradition in your family that you love?",
  'If you could have any animal as a pet, what would it be?',
  "What's the most inspiring book you've ever read?",
  'If you could be a character in any movie, who would you be?',
  "What's a technology that you think will change the world?",
  'If you could attend any major event in history, what would it be?',
  "What's your favorite way to spend a lazy Sunday?",
  'If you could have any three people, living or dead, over for dinner, who would they be?',
  "What's your favorite board game or card game?",
  'If you could master one musical instrument, what would it be?',
  "What's a cause you're passionate about?",
  'If you could have any job in the world, no restrictions, what would it be?',
  "What's the most delicious meal you've ever had?",
  'If you could have a conversation with any animal, what would it be?',
  "What's your favorite childhood game?",
  'If you could visit any fictional world, where would you go?',
  "What's a hobby you've always wanted to try but haven't?",
  'If you could have any car in the world, what would it be?',
  "What's your favorite way to exercise and stay fit?",
  'If you could have any historical artifact, what would it be?',
  "What's a skill you wish you had?",
  'If you could witness any historical event, what would it be?',
  "What's your favorite season and why?",
  'If you could be a character in any book, who would you be?',
  "What's a movie that made you cry?",
  'If you could have any magical ability, what would it be?',
  "What's your favorite way to de-stress?",
  'If you could have any type of pet, exotic or not, what would it be?',
  "What's your favorite way to enjoy nature?",
  'If you could have dinner with any celebrity, who would it be?',
  "What's your favorite way to volunteer and give back to the community?",
  'If you could have any job for a day, what would it be?',
  "What's your favorite childhood cartoon?",
  'If you could be a professional athlete, in what sport would you compete?',
  "What's the most adventurous thing you've ever done?",
  'If you could be a character in any video game, who would you be?',
  "What's your favorite thing about your hometown?",
  'If you could meet any historical figure, who would it be?',
  "What's a goal you have for the next year?",
  'If you could be any superhero, who would you be?',
  "What's your favorite outdoor activity?",
  'If you could learn any language fluently, what would it be?',
  "What's your favorite childhood book?",
  'If you could have any dessert right now, what would it be?',
  "What's a place you've always wanted to visit but haven't?",
  'If you could have dinner with any family member, living or deceased, who would it be?',
  "What's your favorite way to spend time with friends?",
  'If you could be a famous artist, who would you be?',
  "What's your favorite way to learn new things?",
  'If you could have any historical figure as a mentor, who would it be?',
  "What's a skill you have that you're really proud of?",
  'If you could have any view from your window, what would it be?',
  "What's your favorite way to stay organized?",
  'If you could have any animal as a companion, what would it be?',
  "What's your favorite way to pamper yourself?",
  'If you could be a character in any TV show, who would you be?',
  "What's your favorite way to spend a rainy day?",
  'If you could have any type of house, what would it look like?',
  "What's your favorite type of art?",
  'If you could meet any musician, dead or alive, who would it be?',
  "What's your favorite way to show appreciation for someone?",
  'If you could have any job-related superpower, what would it be?',
  "What's your favorite way to celebrate your achievements?",
  'If you could be a character in any comic book, who would you be?',
  "What's a piece of advice you wish you had received earlier in life?",
  'If you could have any movie character as a best friend, who would it be?',
  "What's your favorite way to spend a sunny day?",
  'If you could have any type of garden, what would you grow?',
  "What's your favorite way to learn about different cultures?",
  'If you could meet any inventor, who would it be?',
  "What's your favorite way to practice self-care?",
  'If you could have any job-related gadget, what would it be?',
  "What's your favorite way to support local businesses?",
  'If you could have any historical figure as a close friend, who would it be?',
  "What's your favorite way to stay motivated?",
  'If you could meet any scientist, who would it be?',
  "What's your favorite way to start the day?",
  'If you could have any job-related tool, what would it be?',
  "What's your favorite way to express your creativity?",
  'If you could meet any author, who would it be?',
  "What's your favorite way to stay focused?",
  'If you could have any job-related vehicle, what would it be?',
  "What's your favorite way to relax before bed?",
  'If you could meet any entrepreneur, who would it be?',
  "What's your favorite way to stay positive?",
  'If you could have any job-related uniform, what would it be?',
  "What's your favorite way to stay connected with loved ones?",
  'If you could meet any philosopher, who would it be?',
  "What's your favorite way to recharge your energy?",
  'If you could have any job-related workspace, what would it look like?',
  "What's your favorite way to unwind after a challenging day?",
  'If you could meet any chef, who would it be?',
  "What's your favorite way to practice mindfulness?",
  'If you could have any job-related office equipment, what would it be?',
  "What's your favorite way to stay calm under pressure?",
  'If you could meet any fashion designer, who would it be?',
  "What's your favorite way to maintain a work-life balance?",
  'If you could have any job-related software, what would it be?',
  "What's your favorite way to handle difficult situations?",
  'If you could meet any architect, who would it be?',
  "What's your favorite way to overcome challenges?",
  'If you could have any job-related accessory, what would it be?',
  "What's your favorite way to inspire others?",
  'If you could meet any motivational speaker, who would it be?',
  "What's your favorite way to achieve your goals?",
  'If you could have any job-related badge, what would it be?',
  "What's your favorite way to stay organized in your personal life?",
  'If you could meet any humanitarian, who would it be?',
  "What's your favorite way to stay focused on your priorities?",
  'If you could have any job-related certification, what would it be?',
  "What's your favorite way to make a positive impact in your community?",
  'If you could meet any activist, who would it be?',
  "What's your favorite way to support causes you believe in?",
];
