export const questions = [
  'What is your favorite book and why?',
  'If you could travel to any place in the world, where would you go?',
  "What's a skill you want to learn and why?",
  'What is your favorite movie, and what do you love about it?',
  'If you could have dinner with any historical figure, who would it be and why?',
  "What's the most adventurous thing you've ever done?",
  'If you could visit any fictional world, where would you go?',
  "What's your go-to comfort food?",
  'If you could possess any talent instantly, what would it be?',
  "What's the most beautiful place you've ever been to?",
  'If you could be a character from a book, who would you be and why?',
  "What's your favorite season, and what do you enjoy most about it?",
  'If you could time travel, where and when would you go?',
  "What's a hobby you've always wanted to try but haven't?",
  'If you could have any animal as a pet, what would it be?',
  "What's the best piece of advice you've ever received?",
  'If you could meet any celebrity, who would it be and what would you ask them?',
  "What's your favorite way to unwind after a long day?",
  'If you had a magical power, what would it be and how would you use it?',
  "What's a skill you admire in others and wish you had?",
  'If you could live in any era of history, when would it be?',
  "What's a goal you've set for yourself this year?",
  'If you could donate to any charity, which one would it be and why?',
  "What's your dream job and why does it inspire you?",
  'If you could have any superpower for a day, what would it be?',
  "What's your favorite childhood memory?",
  'If you could learn any language instantly, which one would it be?',
  "What's a place you've always wanted to travel to but haven't yet?",
  'If you could have any job in the world for a day, what would it be?',
  "What's a book that has had a significant impact on your life?",
  'If you could have any dessert right now, what would it be?',
  "What's your favorite way to spend a rainy day?",
  'If you could solve one world problem, what would it be?',
  "What's your favorite type of music, and why does it resonate with you?",
  'If you could have dinner with any fictional character, who would it be and why?',
  "What's a dream you've always had but haven't pursued yet?",
  'If you could meet your younger self, what advice would you give?',
  "What's the most interesting fact you know?",
  'If you could master any skill instantly, what would it be?',
  "What's your favorite thing about the city you live in?",
  'If you could switch lives with someone for a day, who would it be?',
  "What's a cause you're passionate about, and how do you support it?",
  'If you could change one thing about the world, what would it be?',
  "What's a recent accomplishment you're proud of?",
  'If you could have any pet in the world, what would it be?',
  "What's a place you'd love to visit again and why?",
  'If you could have any meal right now, what would it be?',
  "What's your favorite thing to do on weekends?",
  'If you could have any historical figure as a mentor, who would it be?',
  "What's your favorite way to stay active and healthy?",
  'If you could own any piece of artwork, which one would it be?',
  "What's your favorite board game or video game?",
  'If you could master any instrument, what would it be?',
  "What's the most meaningful compliment you've ever received?",
  'If you could have any job in the world without worrying about money, what would it be?',
  "What's your favorite way to show kindness to others?",
  'If you could attend any major event in the past, what would it be?',
  "What's the most valuable lesson you've learned from a mistake?",
  'If you could have a conversation with your future self, what would you ask?',
  "What's the most beautiful natural place you've ever seen?",
  'If you could have dinner with any fictional character, who would it be?',
  "What's your favorite type of cuisine?",
  'If you could have any car, what would it be?',
  "What's your favorite app on your phone?",
  "If you could have any animal's ability, which one would you choose?",
  "What's your favorite childhood cartoon or TV show?",
  'If you could visit any historical era, which one would you choose?',
  "What's your favorite quote or mantra that inspires you?",
  'If you could have any famous chef cook you a meal, who would it be?',
  "What's your favorite way to practice self-care?",
  'If you could meet any famous scientist, who would it be?',
  "What's your favorite type of weather and why?",
  'If you could invent a new gadget, what would it do?',
  "What's your favorite way to relax and unwind?",
  'If you could attend any major event in the future, what would it be?',
  "What's your favorite thing about your cultural background?",
  'If you could have any animal as a companion, what would it be?',
  "What's your favorite way to express your creativity?",
  'If you could learn any dance style, which one would you choose?',
  "What's the most surprising fact you know?",
  'If you could have any fictional character as a best friend, who would it be?',
  "What's your favorite childhood memory related to nature?",
  'If you could have any book instantly memorized, which one would it be?',
  "What's your favorite museum you've ever visited?",
  'If you could attend any major concert, which artist would you love to see?',
  "What's your favorite way to spend time with your family?",
  'If you could have any talent, unrelated to your current skills, what would it be?',
  "What's your favorite holiday and how do you celebrate it?",
  'If you could have any view from your window, what would it be?',
  "What's the most fascinating historical fact you know?",
  "If you could have any animal's communication ability, which one would you choose?",
  "What's your favorite way to practice mindfulness?",
];
